# Generated by Django 5.0.4 on 2026-04-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('letter', 'Letter'), ('circular', 'Circular'), ('memo', 'Memo')], default='letter', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('RECEIVED', 'Received'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_REVIEW', 'In Review'), ('ACTION_TAKEN', 'Action Taken'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notice_events',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_code', models.CharField(max_length=20)),
                ('dept_code', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'reference_counters',
            },
        ),
    ]
