# Generated by Django 5.0.4 on 2026-04-13 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notices', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='receiver_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_notices', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='notice',
            name='receiver_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_notices', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='notice',
            name='sender_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_notices', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='notice',
            name='sender_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_notices', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='noticeevent',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticeevent',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='notices.notice'),
        ),
        migrations.AlterUniqueTogether(
            name='referencecounter',
            unique_together={('org_code', 'dept_code', 'year')},
        ),
    ]
