# Generated by Django 5.0.4 on 2026-04-21 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='receiver_dept',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='receiver_org',
        ),
        migrations.CreateModel(
            name='NoticeReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_receivers', to='notices.notice')),
                ('receiver_dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_notices', to='organizations.department')),
                ('receiver_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_notices', to='organizations.organization')),
            ],
            options={
                'db_table': 'notice_receivers',
                'unique_together': {('notice', 'receiver_org', 'receiver_dept')},
            },
        ),
    ]
