# Generated by Django 5.0.4 on 2026-04-22 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_remove_notice_receiver_dept_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticereceiver',
            name='receiver_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_notices', to='organizations.department'),
        ),
    ]
